function outStruct = createNewAnimalDataStruct(varargin)
    animal = 'RW1';
    genotype = 'WT';
    gender = 'M';
    animal_uid = 'LDF222';
    DOB = NaT;
    preimplant_weight = nan;
    implant_date = NaT;
    implant_age = nan;
    implant_weight = nan;
    recording_data = struct('day',[],'date',NaT,'epoch',[],'epoch_type','',...
                      'environment','','led_orientation','','weight',nan,...
                      'age',nan,'injection','','injection_volume',nan,...
                      'drug_dose',nan,'comments','');
    
    assignVars(varargin)

    outStruct = struct('animal',animal,'genotype',genotype,'gender',gender,...
                       'animal_uid',animal_uid,'DOB',DOB,,...
                       'preimplant_weight',preimplant_weight,...
                       'implant_date',implant_date,'implant_age',implant_age,...
                       'implant_weight',implant_weight,...
                       'recording_data',recording_data);
